packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': 22.19.11
  typescript: 5.9.3
  vitest: 3.2.7

onlyBuiltDependencies:
  - '@azure/msal-node-extensions'
  - '@azure/msal-node-runtime'
  - esbuild
  - keytar
  - lefthook
  - turbo
